### PR TITLE
Support redux-saga 0.13.x

### PR DESCRIPTION
**Pull request by aaronjensen**

### CODE REVIEW

**Comment by colinbate** [comment]
Have you verified that everything still works with 0.13? Looking at the release notes I can't see why it wouldn't, but I don't have the opportunity to test it right now.

**Comment by aaronjensen** [comment]
It works for us

**Comment by colinbate** [comment]
Published as 1.1.1

**Comment by jedrichards** [comment]
0.13.x is working for me too.

**Pull request merged**
